# Generated by Django 4.1 on 2023-11-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='census',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='census',
            name='role',
            field=models.CharField(choices=[(0, 'Only for Hierchical Votings'), (1, 'Balanceado'), (2, 'Colaborador'), (3, 'Coordinador'), (4, 'Presidente')], default='0', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='census',
            unique_together={('voting_id', 'voter_id', 'role')},
        ),
    ]
