# Generated by Django 4.1 on 2023-11-11 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0005_census_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='census',
            unique_together={('voting_id', 'voter_id', 'role')},
        ),
    ]
