# Generated by Django 4.1 on 2023-11-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0005_census_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='census',
            name='role',
            field=models.CharField(choices=[('0', 'Only for Hierchical Votings. Select this if voting isn`t Hierchical'), ('1', 'Balanceado'), ('2', 'Colaborador'), ('3', 'Coordinador'), ('4', 'Presidente')], default='0', max_length=1),
        ),
    ]
