# Generated by Django 4.1 on 2023-12-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='voting_type',
            field=models.CharField(choices=[('S', 'Single Choice'), ('M', 'Multiple Choice'), ('H', 'Hierarchy'), ('Q', 'Many Questions')], default='S', max_length=1),
        ),
    ]
