# Generated by Django 4.1 on 2023-11-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_alter_voting_postproc_alter_voting_tally'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='optionSiNo',
            field=models.BooleanField(default=False, help_text='Marca esta casilla para que las opciones sean Si o No. No podrás añadir más opciones'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='voting_type',
            field=models.CharField(choices=[('S', 'Single Choice'), ('M', 'Multiple Choice'), ('H', 'Hierarchy'), ('Q', 'Many Questions')], max_length=1),
        ),
    ]
