# Generated by Django 4.1 on 2023-11-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_alter_voting_postproc_alter_voting_tally'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='voting_type',
            field=models.CharField(choices=[('S', 'Single Choice'), ('M', 'Multiple Choice'), ('H', 'Hierarchy'), ('Q', 'Many Questions')], default='S', max_length=1),
        ),
    ]
