# Generated by Django 4.1 on 2023-11-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_question_optionsino_alter_voting_voting_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='optionSiNo',
            field=models.BooleanField(default=False, help_text="Marca esta casilla solo si el tipo de votación es 'Single Choice'. No podrás añadir más opciones si esta casilla está marcada."),
        ),
    ]
