# Generated by Django 4.1 on 2023-11-16 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_alter_voting_voting_type'),
        ('voting', '0007_question_third_option_alter_question_optionsino'),
    ]

    operations = [
    ]
