# Generated by Django 4.1 on 2023-11-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_question_third_option_alter_question_optionsino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='third_option',
            field=models.BooleanField(default=False, help_text="Marca esta casilla para añadir una tercera opción con el valor 'Depende'"),
        ),
    ]
