# Generated by Django 4.1 on 2023-12-14 16:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0005_alter_voting_voting_type"),
        ("voting", "0008_alter_question_third_option"),
    ]

    operations = []
