# Generated by Django 4.1 on 2023-11-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_merge_20231126_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='third_option',
            field=models.BooleanField(default=False, help_text="Marca esta casilla para añadir una tercera opción con el valor 'Depende'"),
        ),
    ]
