# Generated by Django 4.1 on 2023-11-26 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_alter_question_third_option'),
        ('voting', '0009_alter_question_third_option'),
    ]

    operations = [
    ]
