# Generated by Django 4.1 on 2023-11-27 09:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0005_alter_voting_questions"),
        ("voting", "0009_merge_20231127_0851"),
    ]

    operations = []
