# Generated by Django 4.1 on 2023-12-16 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_merge_20231214_1614'),
        ('voting', '0010_merge_20231126_1309'),
    ]

    operations = [
    ]
