# Generated by Django 4.1 on 2023-12-13 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_merge_20231116_1019'),
        ('voting', '0010_merge_20231126_1309'),
    ]

    operations = [
    ]
