# Generated by Django 4.1 on 2023-12-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_merge_20231126_1309'),
        ('voting', '0010_merge_20231127_0901'),
    ]

    operations = [
    ]
