# Generated by Django 4.1 on 2023-12-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0012_merge_20231215_1925"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voting",
            name="voting_type",
            field=models.CharField(
                choices=[
                    ("S", "Single Choice"),
                    ("M", "Multiple Choice"),
                    ("H", "Hierarchy"),
                ],
                default="S",
                max_length=1,
            ),
        ),
    ]
