# Generated by Django 4.1 on 2023-12-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostProcessing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting_id', models.PositiveIntegerField()),
                ('question_id', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('DEF', 'DEFAULT'), ('BOR', 'BORDA'), ('DHO', 'DHONDT'), ('PAR', 'PARITY')], default='DEF', max_length=3)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('results', models.JSONField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('voting_id', 'question_id', 'type')},
            },
        ),
    ]
