# Generated by Django 4.1 on 2023-11-23 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_alter_voting_postproc_alter_voting_tally'),
        ('postproc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postprocessing',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='postprocessing',
            name='voting_id',
        ),
        migrations.AddField(
            model_name='postprocessing',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.question'),
        ),
        migrations.AddField(
            model_name='postprocessing',
            name='voting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.voting'),
        ),
        migrations.AlterField(
            model_name='postprocessing',
            name='type',
            field=models.CharField(choices=[('NON', 'NONE'), ('BOR', 'BORDA'), ('DHO', 'DHONDT'), ('PAR', 'SAINT')], default='NON', max_length=3),
        ),
    ]
