# Generated by Django 4.1 on 2023-11-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20180921_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='value',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
