# Generated by Django 4.1 on 2023-11-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_vote_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='value',
        ),
    ]
