# Generated by Django 4.1 on 2023-11-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_vote_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='value',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
