name: release

on: 
    push:
        branches:
            - master
        tags:
            - '*'

permissions:
    contents: write

jobs:
    buildTest:
        uses: Moffinguer/dedice-part-camaron-2/.github/workflows/django.yml@master
        secrets:
            CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

    release:
        needs: buildTest
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Release
              uses: softprops/action-gh-release@v1